---
k3s_version: 'v1.30.2+k3s2'
init_token: '0Z+KqKT12LHk2V6Y+H0jbY7nFeFD8WK65YX+HocGeZwlENLvdSoU/fuVGe59'
extra_server_args: '--node-external-ip {{ ansible_default_ipv4.address }} --flannel-iface {{ ansible_default_ipv4.alias }}' 
extra_agent_args: '--node-external-ip {{ ansible_default_ipv4.address }} --flannel-iface {{ ansible_default_ipv4.alias }}'
